// <auto-generated />
using System;
using Causym;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Causym.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Causym.Modules.Configure.GuildConfiguration", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Causym.Modules.Statistics.ChannelSnapshot", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SnapshotTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "ChannelId", "SnapshotTime");

                    b.ToTable("ChannelSnapshots");
                });

            modelBuilder.Entity("Causym.Modules.Statistics.StatisticsConfig", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("MemberChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SnapshotsEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("StatServers");
                });

            modelBuilder.Entity("Causym.Modules.Statistics.StatisticsSnapshot", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SnapshotTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("CachedMembers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MembersDND")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MembersIdle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MembersOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMessageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "SnapshotTime");

                    b.ToTable("StatSnapshots");
                });

            modelBuilder.Entity("Causym.Modules.Translation.TranslateGuild", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReactionsEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("TranslateGuilds");
                });

            modelBuilder.Entity("Causym.Modules.Translation.TranslatePair", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("DestLang")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("GuildId", "Source");

                    b.ToTable("TranslatePairs");
                });
#pragma warning restore 612, 618
        }
    }
}
