// <auto-generated />
using System;
using Causym;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Causym.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200506021101_init_postgres")]
    partial class init_postgres
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Causym.Modules.Configure.GuildConfiguration", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Prefix")
                        .HasColumnType("text");

                    b.Property<bool>("RespondOnCommandFailure")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Causym.Modules.Statistics.ChannelSnapshot", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("SnapshotTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "ChannelId", "SnapshotTime");

                    b.ToTable("ChannelSnapshots");
                });

            modelBuilder.Entity("Causym.Modules.Statistics.StatisticsConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("MemberChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("SnapshotsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId");

                    b.ToTable("StatServers");
                });

            modelBuilder.Entity("Causym.Modules.Statistics.StatisticsSnapshot", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("SnapshotTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CachedMembers")
                        .HasColumnType("integer");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer");

                    b.Property<int>("MembersDND")
                        .HasColumnType("integer");

                    b.Property<int>("MembersIdle")
                        .HasColumnType("integer");

                    b.Property<int>("MembersOnline")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMessageCount")
                        .HasColumnType("integer");

                    b.HasKey("GuildId", "SnapshotTime");

                    b.ToTable("StatSnapshots");
                });

            modelBuilder.Entity("Causym.Modules.Translation.TranslateGuild", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("ReactionsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId");

                    b.ToTable("TranslateGuilds");
                });

            modelBuilder.Entity("Causym.Modules.Translation.TranslatePair", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Source")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("DestLang")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("GuildId", "Source");

                    b.ToTable("TranslatePairs");
                });
#pragma warning restore 612, 618
        }
    }
}
