name: .NET Core

on: [push]

jobs:
  buildubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - uses: NuGet/setup-nuget@v1.0.2
    - name: Setup NuGet Sources
      run: nuget sources add -name "MyGet" -Source "https://www.myget.org/F/quahu/api/v3/index.json"
    - name: dotnet Restore
      run: dotnet restore
    - name: Build with dotnet
      run: dotnet build --configuration Release  
